### ISSUE TITLE
Can't reboot to Hekate from emuMMC

### ISSUE THREAD

**Issue by jjhaywor** [bemardev/HekateBrew#1]
Running latest atmosphere and Hekate. Launching from applet mode or normal mode and pressing ZL freezes the app. Can still exit by pressing the HOME button.

**Comment by bemardev** [comment]
Sorry for that.
I've fixed it in 0.9, you can find it on the release page.
(Please remove HekateBrew.nro in your switch folder before applying the new release; from now this nro is located in the HekateBrew folder)

**Comment by jjhaywor** [comment]
Awesome, thank you!
